#!/bin/bash

install-isaacaa () {
   # Are we correctly installed?
   echo "My custom environment is not yet installed!"

   cd ~ && mkdir .isaacaa
   cd .isaacaa && git clone https://github.com/Isaac-a95/isaacaa-env.git .

   copy-isaacaa
   if [ ! -f ~/.vim/bundle/Vundle.vim/README.md ]; then
      git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
   fi
   vim +PluginInstall +qall
}

copy-isaacaa() {
   cd ~/.isaacaa
   cp bash_isaacaa-install ../.bash_isaacaa-install
   cp vimrc ../.vimrc
   cp bash_isaacaa-env ../.bash_isaacaa-env
   cp git-completition.sh ../.git-completition.sh
   cd ~
}

update-isaacaa () {
   # Check if we are at the lastest possible version
   cd ~/.isaacaa && git pull origin master
   copy-isaacaa
}

if [ ! -d ~/.isaacaa ]; then
   echo "Run install-isaacaa for installing the environment!"
   #install-isaacaa
fi

. ~/.bash_isaacaa-env
